name: Firebase Hosting Continuous Deployment 

on: 
  push:
    branches: [ master ]
    
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1 
      - uses: subosito/flutter-action@v1
        with:
          channel: 'dev'
          
      - run: flutter config --enable-web
        
  
